---
:concurrency: 5
:timeout: 25
:verbose: false
:queues:
  - [critical, 3]
  - [default, 2]
  - [mailers, 1]
  - [low, 1]

# Production settings
production:
  :concurrency: 25
  :queues:
  - [critical, 5]
  - [default, 3]
  - [mailers, 2]
  - [low, 1]

# Staging settings
staging:
  :concurrency: 10
  :queues:
  - [critical, 4]
  - [default, 2]
  - [mailers, 2]
  - [low, 1]

  